// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import StimulusReflex from 'stimulus_reflex'
import { application } from "./application"

import ThDatePicker from '../components/th_datepicker_controller'
import TrixCustomization from '../components/trix_customization_controller'
import NestedForm from 'stimulus-rails-nested-form'
import Sortable from 'stimulus-sortable'

application.register('datepicker', ThDatePicker)
application.register('trix-customization', TrixCustomization)
application.register('nested-form', NestedForm)
application.register('sortable', Sortable)

import FormController from "./form_controller"
import EformController from "./eform_controller"
import NotificationController from "./notification_controller"

import SelectFieldController from "./select_field_controller"
import SelectSearchFieldController from "./select_search_field_controller"
import LocationFieldController from "./location_field_controller"
import ListFieldController from "./list_field_controller"
import RadioButtonsFieldController from "./radio_buttons_field_controller"
import GroupFieldController from "./group_field_controller"
import CopyAddressFieldController from "./copy_address_field_controller"
import FileFieldController from "./file_field_controller"
import FileMultipleFieldController from "./file_multiple_field_controller"
import BasicInformationFieldController from "./basic_information_field_controller"
import CheckboxFieldController from "./checkbox_field_controller"
import TagFieldController from "./tag_field_controller"
import TitleFieldController from "./title_field_controller"
import ContentFieldController from "./content_field_controller"
import OrganizationCheckingController from "./organization_checking_controller"
import PowerOfAttorneyFieldController from "./power_of_attorney_field_controller"

application.register("form", FormController)
application.register("eform", EformController)
application.register("notification", NotificationController)

application.register("select-field", SelectFieldController)
application.register("select-search-field", SelectSearchFieldController)
application.register("location-field", LocationFieldController)
application.register("list-field", ListFieldController)
application.register("radio-buttons-field", RadioButtonsFieldController)
//application.register("group-field", GroupFieldController)
application.register("copy-address-field", CopyAddressFieldController)
application.register("file-field", FileFieldController)
application.register("file-multiple-field", FileMultipleFieldController)
application.register("basic-information-field", BasicInformationFieldController)
application.register("checkbox-field", CheckboxFieldController)
application.register("tag-field", TagFieldController)
application.register("title-field", TitleFieldController)
application.register("content-field", ContentFieldController)
application.register("group-field", GroupFieldController)
application.register("organization-checking", OrganizationCheckingController)
application.register("power-of-attorney-field", PowerOfAttorneyFieldController)

StimulusReflex.initialize(application, { debug: false })
